const OPEN_WEATHER_API = 'ENTER_YOUR_OPEN_WEATHER_API_KEY';

const TABLE_NAME = 'ENTER_YOUR_TABLE_NAME';
const REGION = 'ENTER_YOUR_DYNAMO_DB_REGION';
const ACCESS_KEY_ID = 'ENTER_YOUR_ACCESS_KEY_ID';
const SECRET_ACCESS_KEY = 'ENTER_YOUR_SECRET_ACCESS_KEY_ID';

module.exports = { OPEN_WEATHER_API, TABLE_NAME, REGION, ACCESS_KEY_ID, SECRET_ACCESS_KEY };